---

- name: Install powerline-shell pip package for fancy PS1 prompt
  pip:
    name: powerline-shell
    state: present
  become: yes

- name: Ensure ~/.config/powerline-shell/ directory
  file:
    dest: "{{ ansible_env.HOME }}/.config/powerline-shell"
    state: directory

- name: Template powerline-shell config.json to ~/.config/powerline-shell/config.json
  template:
    src: home/user/.config/powerline-shell/config.json.j2
    dest: "{{ ansible_env.HOME }}/.config/powerline-shell/config.json"
